export const PLANNER_JSON_DIRECTORY = "/Users/ryansadler/Library/Mobile Documents/com~apple~CloudDocs/Developer/Live Pages/Lesson Planner/json";

export function classScheduleImportPrompt(): string {
  return `Create one Lesson Planner class-and-schedule JSON file. Return JSON only: no Markdown, explanation, SQL, IDs, URLs, credentials, or extra fields. Do not add data that was not supplied to you. Save the finished file in ${PLANNER_JSON_DIRECTORY} with a .json extension, then I will choose it manually in Lesson Planner.\n\nUse exactly this shape:\n{\n  "version": 1,\n  "class": {\n    "name": "Class name",\n    "group": "Optional group or level",\n    "coach": "Optional coach name",\n    "notes": "Optional private note",\n    "students": [{ "name": "Student name", "notes": "Optional private note" }],\n    "schedule": [{ "day": "Monday", "start": "3:30 PM", "end": "4:00 PM", "event": "Floor", "areas": ["F2"], "notes": "Optional private note" }]\n  }\n}\n\nUse only a weekday, Daily, Every day, or YYYY-MM-DD for day. Each schedule row must end after it starts. The Planner creates its own local IDs and only adds a new class after I review the file.`;
}

export function fullScheduleImportPrompt(): string {
  return `Create one privacy-safe Lesson Planner full-gym schedule JSON file. Return JSON only: no Markdown, explanation, roster/student data, media, URLs, source paths, raw notes, credentials, SQL, or extra fields. Every privacy flag must be false. Save the finished file in ${PLANNER_JSON_DIRECTORY} with a .json extension, then I will choose it manually in Lesson Planner.\n\nUse format "lesson-planner-safe-schedule" and version 1. The root must contain only format, version, privacy, and schedule. schedule must contain only sourceId, scheduleId, revision, timezone, effectiveStart, effectiveEnd, calendarWeekRule, equipment, timeBlocks, and collisionWarnings.\n\nEach timeBlocks record must contain bookingId, day (Mon/Tues/Wed/Thurs/Fri/Sat/Sun), week (Odd or Even), group, startMinute, endMinute, canonicalEventLabel, eventLabel, equipment, activityType (rotation/open/support/conditioning/warmup), confidence (high/medium/low), and reviewStatus (auto_extracted/color_inferred/color_inferred_needs_review/needs_review). Use whole minutes, unique opaque bookingIds, and endMinute greater than startMinute. This file is advisory only: it must never reserve equipment or change the source schedule.`;
}
